// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 5.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'dashboard_sgtvt';

  static const String assets_icons_logos_logo_development_png = 'assets/icons/logos/logo-development.png';
  static const String dashboard_sgtvt$assets_icons_logos_logo_development_png = 'packages/dashboard_sgtvt/assets/icons/logos/logo-development.png';

  static const String assets_icons_logos_logo_production_png = 'assets/icons/logos/logo-production.png';
  static const String dashboard_sgtvt$assets_icons_logos_logo_production_png = 'packages/dashboard_sgtvt/assets/icons/logos/logo-production.png';

  static const String assets_icons_logos_logo_staging_png = 'assets/icons/logos/logo-staging.png';
  static const String dashboard_sgtvt$assets_icons_logos_logo_staging_png = 'packages/dashboard_sgtvt/assets/icons/logos/logo-staging.png';

  static const String assets_images_drawer_header_background_jpeg = 'assets/images/drawer_header_background.jpeg';
  static const String dashboard_sgtvt$assets_images_drawer_header_background_jpeg = 'packages/dashboard_sgtvt/assets/images/drawer_header_background.jpeg';

  static const String assets_images_login_background_png = 'assets/images/login_background.png';
  static const String dashboard_sgtvt$assets_images_login_background_png = 'packages/dashboard_sgtvt/assets/images/login_background.png';
}
